# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ken/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/ken/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ken/Desktop/MHPC/LJMB

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ken/Desktop/MHPC/LJMB

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ken/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ken/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ken/Desktop/MHPC/LJMB/CMakeFiles /home/ken/Desktop/MHPC/LJMB//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ken/Desktop/MHPC/LJMB/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MAIN.x

# Build rule for target.
MAIN.x: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MAIN.x
.PHONY : MAIN.x

# fast build rule for target.
MAIN.x/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAIN.x.dir/build.make CMakeFiles/MAIN.x.dir/build
.PHONY : MAIN.x/fast

#=============================================================================
# Target rules for targets named Timer

# Build rule for target.
Timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Timer
.PHONY : Timer

# fast build rule for target.
Timer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Timer.dir/build.make CMakeFiles/Timer.dir/build
.PHONY : Timer/fast

#=============================================================================
# Target rules for targets named mdlib

# Build rule for target.
mdlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdlib
.PHONY : mdlib

# fast build rule for target.
mdlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/build
.PHONY : mdlib/fast

src/cleanup.o: src/cleanup.c.o
.PHONY : src/cleanup.o

# target to build an object file
src/cleanup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/cleanup.c.o
.PHONY : src/cleanup.c.o

src/cleanup.i: src/cleanup.c.i
.PHONY : src/cleanup.i

# target to preprocess a source file
src/cleanup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/cleanup.c.i
.PHONY : src/cleanup.c.i

src/cleanup.s: src/cleanup.c.s
.PHONY : src/cleanup.s

# target to generate assembly for a file
src/cleanup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/cleanup.c.s
.PHONY : src/cleanup.c.s

src/comp.o: src/comp.c.o
.PHONY : src/comp.o

# target to build an object file
src/comp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/comp.c.o
.PHONY : src/comp.c.o

src/comp.i: src/comp.c.i
.PHONY : src/comp.i

# target to preprocess a source file
src/comp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/comp.c.i
.PHONY : src/comp.c.i

src/comp.s: src/comp.c.s
.PHONY : src/comp.s

# target to generate assembly for a file
src/comp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/comp.c.s
.PHONY : src/comp.c.s

src/init.o: src/init.c.o
.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/init.c.s
.PHONY : src/init.c.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAIN.x.dir/build.make CMakeFiles/MAIN.x.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAIN.x.dir/build.make CMakeFiles/MAIN.x.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MAIN.x.dir/build.make CMakeFiles/MAIN.x.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/output.o: src/output.c.o
.PHONY : src/output.o

# target to build an object file
src/output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/output.c.o
.PHONY : src/output.c.o

src/output.i: src/output.c.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/output.c.i
.PHONY : src/output.c.i

src/output.s: src/output.c.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/output.c.s
.PHONY : src/output.c.s

src/structs.o: src/structs.c.o
.PHONY : src/structs.o

# target to build an object file
src/structs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/structs.c.o
.PHONY : src/structs.c.o

src/structs.i: src/structs.c.i
.PHONY : src/structs.i

# target to preprocess a source file
src/structs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/structs.c.i
.PHONY : src/structs.c.i

src/structs.s: src/structs.c.s
.PHONY : src/structs.s

# target to generate assembly for a file
src/structs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/structs.c.s
.PHONY : src/structs.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/verlet.o: src/verlet.c.o
.PHONY : src/verlet.o

# target to build an object file
src/verlet.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/verlet.c.o
.PHONY : src/verlet.c.o

src/verlet.i: src/verlet.c.i
.PHONY : src/verlet.i

# target to preprocess a source file
src/verlet.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/verlet.c.i
.PHONY : src/verlet.c.i

src/verlet.s: src/verlet.c.s
.PHONY : src/verlet.s

# target to generate assembly for a file
src/verlet.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdlib.dir/build.make CMakeFiles/mdlib.dir/src/verlet.c.s
.PHONY : src/verlet.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MAIN.x"
	@echo "... Timer"
	@echo "... mdlib"
	@echo "... src/cleanup.o"
	@echo "... src/cleanup.i"
	@echo "... src/cleanup.s"
	@echo "... src/comp.o"
	@echo "... src/comp.i"
	@echo "... src/comp.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/structs.o"
	@echo "... src/structs.i"
	@echo "... src/structs.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/verlet.o"
	@echo "... src/verlet.i"
	@echo "... src/verlet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

